### ISSUE TITLE
Fails to unzip on OS X

### ISSUE THREAD

**Issue by respectTheCode** [xeodou/gulp-atom#8]
The file that is getting downloaded doesn't appear to be a zip file. I get this error.

````
node_modules/gulp-atom/lib/index.js:205
      throw new util.PluginError(PLUGIN_NAME, results.stderr || 'unknow error
            ^
Error in plugin 'gulp-atom-shell'
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

**Comment by xeodou** [comment]
@respectTheCode Which version do you use and which version of `atom-shell` you tring to download ?

**Comment by xeodou** [comment]
And what platform you trying to build.

**Comment by respectTheCode** [comment]
I am on OS X 10.10 and trying to use v0.24.0

```javascript
var gulp = require("gulp");
var atom = require("gulp-atom");

gulp.task("atom", function () {
	return atom({
		srcPath: "./compile",
		releasePath: "./build",
		cachePath: "./cache",
		version: "v0.24.0",
		rebuild: false,
		platforms: ["darwin-x64"]
	});
});

```

**Comment by xeodou** [comment]
@respectTheCode  Atom team has change their repo name  https://github.com/atom/electron/releases
I will push a fix quickly.

**Comment by xeodou** [comment]
@respectTheCode I have push the new version gulp-atom v0.1.0. I think this is will working now.

**Comment by respectTheCode** [comment]
That did it. Thanks.

**Comment by malonehedges** [comment]
@xeodou I am still getting this error. 

First run displays this error message:

```txt
/Users/malonehedges/Documents/Programming/myproject/node_modules/gulp-atom/lib/index.js:212
      throw new util.PluginError(PLUGIN_NAME, results.stderr || 'unknow error 
            ^
Error in plugin 'gulp-atom-shell'
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/malonehedges/Documents/Programming/myproject/cache/v0.28.1/electron-v0.28.1-darwin-x64.zip or
        /Users/malonehedges/Documents/Programming/myproject/cache/v0.28.1/electron-v0.28.1-darwin-x64.zip.zip, and cannot find /Users/malonehedges/Documents/Programming/myproject/cache/v0.28.1/electron-v0.28.1-darwin-x64.zip.ZIP, period.

  at ChildProcess.<anonymous> (/Users/malonehedges/Documents/Programming/myproject/node_modules/gulp-atom/lib/index.js:212:13)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

If I run gulp after the first time I get this error:
```txt
/Users/malonehedges/Documents/Programming/myproject/node_modules/gulp-atom/lib/index.js:212
      throw new util.PluginError(PLUGIN_NAME, results.stderr || 'unknow error 
            ^
Error in plugin 'gulp-atom-shell'
unknow error , maybe you can try delete the zip packages.
  at ChildProcess.<anonymous> (/Users/malonehedges/Documents/Programming/myproject/node_modules/gulp-atom/lib/index.js:212:13)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

I am using `"gulp-atom": "^0.1.0"`.

**Comment by xeodou** [comment]
Hmm, i will have a look.


Best

Xeodou

**Comment by beng** [comment]
@malonehedges I ran into that error as well. I was able to fix it by deleting the zip file in my cache directory and re-running my script.

**Comment by mikelittman** [comment]
I'm still having this issue. Anyone else?

**Comment by duanearnett** [comment]
@mikelittman I need to bump the version of electron that was being downloaded for my project. I guess the older releases aren't available anymore.  v0.36.8 Is working well
